-- Script para corrigir tipos de dados das colunas ID
-- Converte INT para BIGINT para compatibilidade com JPA

USE ecommerce_bd;

-- Alterar tabela Armazem
ALTER TABLE Armazem MODIFY COLUMN id BIGINT AUTO_INCREMENT; 
ALTER TABLE Usuario MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE Telefone MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE Endereco MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE Produto MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE Carrinho MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE ItemCarrinho MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE Pedido MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE ItemPedido MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE Pagamento MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE Fornecedor MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE FornecedorProduto MODIFY COLUMN id BIGINT AUTO_INCREMENT;

-- Verificar se as alterações foram aplicadas
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'ecommerce_bd' 
AND COLUMN_NAME = 'id'
ORDER BY TABLE_NAME;
